CREATE TABLE IF NOT EXISTS CUSTOMER (
    id         INT(4)        NOT NULL UNIQUE AUTO_INCREMENT,
	firstname  NVARCHAR(30)  DEFAULT NULL,
	lastname   NVARCHAR(30)  DEFAULT NULL,
	sex        VARCHAR(10)   DEFAULT NULL,
	language   VARCHAR(20)   DEFAULT NULL,
	engagement DECIMAL(5,2)  DEFAULT NULL,
	email      NVARCHAR(50)  DEFAULT NULL,
	phone      VARCHAR(25)   DEFAULT NULL,
	PRIMARY KEY (id)
    );

CREATE UNIQUE INDEX IF NOT EXISTS `CUSTOMER.id.IDX_UNIQUE` ON CUSTOMER (id ASC);
